// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feobjects/feobjects.proto

/*
Package feobjects is a generated protocol buffer package.

It is generated from these files:
	feobjects/feobjects.proto

It has these top-level messages:
	CompiledBoardEntity
	CompiledThreadEntity
	CompiledPostEntity
	CompiledUserEntity
	CompiledContentSignalsEntity
	ExplainedSignalEntity
	CompiledUserSignalsEntity
	AmbientBoardEntity
	BackendAmbientStatus
	FrontendAmbientStatus
	CompiledNotification
	ReportsTabEntry
*/
package feobjects

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationType int32

const (
	NotificationType_UNKNOWN_NOTIFICATION_TYPE NotificationType = 0
	NotificationType_REPLY_TO_THREAD           NotificationType = 1
	NotificationType_REPLY_TO_POST             NotificationType = 2
)

var NotificationType_name = map[int32]string{
	0: "UNKNOWN_NOTIFICATION_TYPE",
	1: "REPLY_TO_THREAD",
	2: "REPLY_TO_POST",
}
var NotificationType_value = map[string]int32{
	"UNKNOWN_NOTIFICATION_TYPE": 0,
	"REPLY_TO_THREAD":           1,
	"REPLY_TO_POST":             2,
}

func (x NotificationType) String() string {
	return proto.EnumName(NotificationType_name, int32(x))
}
func (NotificationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CompiledBoardEntity struct {
	Fingerprint            string                        `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	SelfCreated            bool                          `protobuf:"varint,2,opt,name=SelfCreated" json:"SelfCreated,omitempty"`
	Name                   string                        `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Description            string                        `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	CompiledContentSignals *CompiledContentSignalsEntity `protobuf:"bytes,5,opt,name=CompiledContentSignals" json:"CompiledContentSignals,omitempty"`
	Owner                  *CompiledUserEntity           `protobuf:"bytes,6,opt,name=Owner" json:"Owner,omitempty"`
	BoardOwners            []string                      `protobuf:"bytes,7,rep,name=BoardOwners" json:"BoardOwners,omitempty"`
	Creation               int64                         `protobuf:"varint,8,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate             int64                         `protobuf:"varint,9,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	Meta                   string                        `protobuf:"bytes,10,opt,name=Meta" json:"Meta,omitempty"`
	ChildThreads           []*CompiledThreadEntity       `protobuf:"bytes,11,rep,name=ChildThreads" json:"ChildThreads,omitempty"`
	ThreadsCount           int32                         `protobuf:"varint,12,opt,name=ThreadsCount" json:"ThreadsCount,omitempty"`
	UserCount              int32                         `protobuf:"varint,13,opt,name=UserCount" json:"UserCount,omitempty"`
	Subscribed             bool                          `protobuf:"varint,14,opt,name=Subscribed" json:"Subscribed,omitempty"`
	Notify                 bool                          `protobuf:"varint,15,opt,name=Notify" json:"Notify,omitempty"`
	LastSeen               int64                         `protobuf:"varint,16,opt,name=LastSeen" json:"LastSeen,omitempty"`
	SFWListed              bool                          `protobuf:"varint,17,opt,name=SFWListed" json:"SFWListed,omitempty"`
}

func (m *CompiledBoardEntity) Reset()                    { *m = CompiledBoardEntity{} }
func (m *CompiledBoardEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledBoardEntity) ProtoMessage()               {}
func (*CompiledBoardEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CompiledBoardEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledBoardEntity) GetSelfCreated() bool {
	if m != nil {
		return m.SelfCreated
	}
	return false
}

func (m *CompiledBoardEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompiledBoardEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CompiledBoardEntity) GetCompiledContentSignals() *CompiledContentSignalsEntity {
	if m != nil {
		return m.CompiledContentSignals
	}
	return nil
}

func (m *CompiledBoardEntity) GetOwner() *CompiledUserEntity {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CompiledBoardEntity) GetBoardOwners() []string {
	if m != nil {
		return m.BoardOwners
	}
	return nil
}

func (m *CompiledBoardEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledBoardEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledBoardEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledBoardEntity) GetChildThreads() []*CompiledThreadEntity {
	if m != nil {
		return m.ChildThreads
	}
	return nil
}

func (m *CompiledBoardEntity) GetThreadsCount() int32 {
	if m != nil {
		return m.ThreadsCount
	}
	return 0
}

func (m *CompiledBoardEntity) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *CompiledBoardEntity) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

func (m *CompiledBoardEntity) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func (m *CompiledBoardEntity) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *CompiledBoardEntity) GetSFWListed() bool {
	if m != nil {
		return m.SFWListed
	}
	return false
}

type CompiledThreadEntity struct {
	Fingerprint            string                        `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Board                  string                        `protobuf:"bytes,2,opt,name=Board" json:"Board,omitempty"`
	SelfCreated            bool                          `protobuf:"varint,3,opt,name=SelfCreated" json:"SelfCreated,omitempty"`
	Name                   string                        `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	Body                   string                        `protobuf:"bytes,5,opt,name=Body" json:"Body,omitempty"`
	Link                   string                        `protobuf:"bytes,6,opt,name=Link" json:"Link,omitempty"`
	CompiledContentSignals *CompiledContentSignalsEntity `protobuf:"bytes,7,opt,name=CompiledContentSignals" json:"CompiledContentSignals,omitempty"`
	Owner                  *CompiledUserEntity           `protobuf:"bytes,8,opt,name=Owner" json:"Owner,omitempty"`
	Creation               int64                         `protobuf:"varint,9,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate             int64                         `protobuf:"varint,10,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	Meta                   string                        `protobuf:"bytes,11,opt,name=Meta" json:"Meta,omitempty"`
	Children               []*CompiledPostEntity         `protobuf:"bytes,12,rep,name=Children" json:"Children,omitempty"`
	PostsCount             int32                         `protobuf:"varint,13,opt,name=PostsCount" json:"PostsCount,omitempty"`
	Score                  float64                       `protobuf:"fixed64,14,opt,name=Score" json:"Score,omitempty"`
}

func (m *CompiledThreadEntity) Reset()                    { *m = CompiledThreadEntity{} }
func (m *CompiledThreadEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledThreadEntity) ProtoMessage()               {}
func (*CompiledThreadEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CompiledThreadEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledThreadEntity) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *CompiledThreadEntity) GetSelfCreated() bool {
	if m != nil {
		return m.SelfCreated
	}
	return false
}

func (m *CompiledThreadEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompiledThreadEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CompiledThreadEntity) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *CompiledThreadEntity) GetCompiledContentSignals() *CompiledContentSignalsEntity {
	if m != nil {
		return m.CompiledContentSignals
	}
	return nil
}

func (m *CompiledThreadEntity) GetOwner() *CompiledUserEntity {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CompiledThreadEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledThreadEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledThreadEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledThreadEntity) GetChildren() []*CompiledPostEntity {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *CompiledThreadEntity) GetPostsCount() int32 {
	if m != nil {
		return m.PostsCount
	}
	return 0
}

func (m *CompiledThreadEntity) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type CompiledPostEntity struct {
	Fingerprint            string                        `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Board                  string                        `protobuf:"bytes,2,opt,name=Board" json:"Board,omitempty"`
	Thread                 string                        `protobuf:"bytes,3,opt,name=Thread" json:"Thread,omitempty"`
	Parent                 string                        `protobuf:"bytes,4,opt,name=Parent" json:"Parent,omitempty"`
	SelfCreated            bool                          `protobuf:"varint,5,opt,name=SelfCreated" json:"SelfCreated,omitempty"`
	Body                   string                        `protobuf:"bytes,6,opt,name=Body" json:"Body,omitempty"`
	CompiledContentSignals *CompiledContentSignalsEntity `protobuf:"bytes,7,opt,name=CompiledContentSignals" json:"CompiledContentSignals,omitempty"`
	Owner                  *CompiledUserEntity           `protobuf:"bytes,8,opt,name=Owner" json:"Owner,omitempty"`
	Creation               int64                         `protobuf:"varint,9,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate             int64                         `protobuf:"varint,10,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	Meta                   string                        `protobuf:"bytes,11,opt,name=Meta" json:"Meta,omitempty"`
	Children               []*CompiledPostEntity         `protobuf:"bytes,12,rep,name=Children" json:"Children,omitempty"`
}

func (m *CompiledPostEntity) Reset()                    { *m = CompiledPostEntity{} }
func (m *CompiledPostEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledPostEntity) ProtoMessage()               {}
func (*CompiledPostEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CompiledPostEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledPostEntity) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *CompiledPostEntity) GetThread() string {
	if m != nil {
		return m.Thread
	}
	return ""
}

func (m *CompiledPostEntity) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CompiledPostEntity) GetSelfCreated() bool {
	if m != nil {
		return m.SelfCreated
	}
	return false
}

func (m *CompiledPostEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CompiledPostEntity) GetCompiledContentSignals() *CompiledContentSignalsEntity {
	if m != nil {
		return m.CompiledContentSignals
	}
	return nil
}

func (m *CompiledPostEntity) GetOwner() *CompiledUserEntity {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CompiledPostEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledPostEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledPostEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledPostEntity) GetChildren() []*CompiledPostEntity {
	if m != nil {
		return m.Children
	}
	return nil
}

type CompiledUserEntity struct {
	Fingerprint         string                     `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	NonCanonicalName    string                     `protobuf:"bytes,2,opt,name=NonCanonicalName" json:"NonCanonicalName,omitempty"`
	Creation            int64                      `protobuf:"varint,3,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate          int64                      `protobuf:"varint,4,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	LastRefreshed       int64                      `protobuf:"varint,5,opt,name=LastRefreshed" json:"LastRefreshed,omitempty"`
	CompiledUserSignals *CompiledUserSignalsEntity `protobuf:"bytes,6,opt,name=CompiledUserSignals" json:"CompiledUserSignals,omitempty"`
	Expiry              int64                      `protobuf:"varint,7,opt,name=Expiry" json:"Expiry,omitempty"`
	Info                string                     `protobuf:"bytes,8,opt,name=Info" json:"Info,omitempty"`
	Meta                string                     `protobuf:"bytes,9,opt,name=Meta" json:"Meta,omitempty"`
}

func (m *CompiledUserEntity) Reset()                    { *m = CompiledUserEntity{} }
func (m *CompiledUserEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledUserEntity) ProtoMessage()               {}
func (*CompiledUserEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CompiledUserEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledUserEntity) GetNonCanonicalName() string {
	if m != nil {
		return m.NonCanonicalName
	}
	return ""
}

func (m *CompiledUserEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledUserEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledUserEntity) GetLastRefreshed() int64 {
	if m != nil {
		return m.LastRefreshed
	}
	return 0
}

func (m *CompiledUserEntity) GetCompiledUserSignals() *CompiledUserSignalsEntity {
	if m != nil {
		return m.CompiledUserSignals
	}
	return nil
}

func (m *CompiledUserEntity) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *CompiledUserEntity) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CompiledUserEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type CompiledContentSignalsEntity struct {
	TargetFingerprint string `protobuf:"bytes,1,opt,name=TargetFingerprint" json:"TargetFingerprint,omitempty"`
	// ATD
	Upvotes            int32                    `protobuf:"varint,2,opt,name=Upvotes" json:"Upvotes,omitempty"`
	Downvotes          int32                    `protobuf:"varint,3,opt,name=Downvotes" json:"Downvotes,omitempty"`
	SelfUpvoted        bool                     `protobuf:"varint,4,opt,name=SelfUpvoted" json:"SelfUpvoted,omitempty"`
	SelfDownvoted      bool                     `protobuf:"varint,5,opt,name=SelfDownvoted" json:"SelfDownvoted,omitempty"`
	SelfATDCreation    int64                    `protobuf:"varint,6,opt,name=SelfATDCreation" json:"SelfATDCreation,omitempty"`
	SelfATDLastUpdate  int64                    `protobuf:"varint,7,opt,name=SelfATDLastUpdate" json:"SelfATDLastUpdate,omitempty"`
	SelfATDFingerprint string                   `protobuf:"bytes,8,opt,name=SelfATDFingerprint" json:"SelfATDFingerprint,omitempty"`
	Reports            []*ExplainedSignalEntity `protobuf:"bytes,9,rep,name=Reports" json:"Reports,omitempty"`
	// bool SelfReported = 10;
	ModBlocks        []*ExplainedSignalEntity `protobuf:"bytes,11,rep,name=ModBlocks" json:"ModBlocks,omitempty"`
	ModApprovals     []*ExplainedSignalEntity `protobuf:"bytes,12,rep,name=ModApprovals" json:"ModApprovals,omitempty"`
	ByMod            bool                     `protobuf:"varint,13,opt,name=ByMod" json:"ByMod,omitempty"`
	ByFollowedPerson bool                     `protobuf:"varint,14,opt,name=ByFollowedPerson" json:"ByFollowedPerson,omitempty"`
	ByBlockedPerson  bool                     `protobuf:"varint,15,opt,name=ByBlockedPerson" json:"ByBlockedPerson,omitempty"`
	ByOP             bool                     `protobuf:"varint,16,opt,name=ByOP" json:"ByOP,omitempty"`
	ModBlocked       bool                     `protobuf:"varint,17,opt,name=ModBlocked" json:"ModBlocked,omitempty"`
	ModApproved      bool                     `protobuf:"varint,18,opt,name=ModApproved" json:"ModApproved,omitempty"`
	LastRefreshed    int64                    `protobuf:"varint,19,opt,name=LastRefreshed" json:"LastRefreshed,omitempty"`
	SelfModApproved  bool                     `protobuf:"varint,20,opt,name=SelfModApproved" json:"SelfModApproved,omitempty"`
	SelfModBlocked   bool                     `protobuf:"varint,21,opt,name=SelfModBlocked" json:"SelfModBlocked,omitempty"`
	SelfModIgnored   bool                     `protobuf:"varint,22,opt,name=SelfModIgnored" json:"SelfModIgnored,omitempty"`
	SelfReported     bool                     `protobuf:"varint,23,opt,name=SelfReported" json:"SelfReported,omitempty"`
}

func (m *CompiledContentSignalsEntity) Reset()                    { *m = CompiledContentSignalsEntity{} }
func (m *CompiledContentSignalsEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledContentSignalsEntity) ProtoMessage()               {}
func (*CompiledContentSignalsEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CompiledContentSignalsEntity) GetTargetFingerprint() string {
	if m != nil {
		return m.TargetFingerprint
	}
	return ""
}

func (m *CompiledContentSignalsEntity) GetUpvotes() int32 {
	if m != nil {
		return m.Upvotes
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetDownvotes() int32 {
	if m != nil {
		return m.Downvotes
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfUpvoted() bool {
	if m != nil {
		return m.SelfUpvoted
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfDownvoted() bool {
	if m != nil {
		return m.SelfDownvoted
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfATDCreation() int64 {
	if m != nil {
		return m.SelfATDCreation
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfATDLastUpdate() int64 {
	if m != nil {
		return m.SelfATDLastUpdate
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfATDFingerprint() string {
	if m != nil {
		return m.SelfATDFingerprint
	}
	return ""
}

func (m *CompiledContentSignalsEntity) GetReports() []*ExplainedSignalEntity {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *CompiledContentSignalsEntity) GetModBlocks() []*ExplainedSignalEntity {
	if m != nil {
		return m.ModBlocks
	}
	return nil
}

func (m *CompiledContentSignalsEntity) GetModApprovals() []*ExplainedSignalEntity {
	if m != nil {
		return m.ModApprovals
	}
	return nil
}

func (m *CompiledContentSignalsEntity) GetByMod() bool {
	if m != nil {
		return m.ByMod
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetByFollowedPerson() bool {
	if m != nil {
		return m.ByFollowedPerson
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetByBlockedPerson() bool {
	if m != nil {
		return m.ByBlockedPerson
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetByOP() bool {
	if m != nil {
		return m.ByOP
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetModBlocked() bool {
	if m != nil {
		return m.ModBlocked
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetModApproved() bool {
	if m != nil {
		return m.ModApproved
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetLastRefreshed() int64 {
	if m != nil {
		return m.LastRefreshed
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfModApproved() bool {
	if m != nil {
		return m.SelfModApproved
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfModBlocked() bool {
	if m != nil {
		return m.SelfModBlocked
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfModIgnored() bool {
	if m != nil {
		return m.SelfModIgnored
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfReported() bool {
	if m != nil {
		return m.SelfReported
	}
	return false
}

type ExplainedSignalEntity struct {
	SourceFp   string `protobuf:"bytes,1,opt,name=SourceFp" json:"SourceFp,omitempty"`
	Reason     string `protobuf:"bytes,2,opt,name=Reason" json:"Reason,omitempty"`
	Creation   int64  `protobuf:"varint,3,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate int64  `protobuf:"varint,4,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
}

func (m *ExplainedSignalEntity) Reset()                    { *m = ExplainedSignalEntity{} }
func (m *ExplainedSignalEntity) String() string            { return proto.CompactTextString(m) }
func (*ExplainedSignalEntity) ProtoMessage()               {}
func (*ExplainedSignalEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExplainedSignalEntity) GetSourceFp() string {
	if m != nil {
		return m.SourceFp
	}
	return ""
}

func (m *ExplainedSignalEntity) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ExplainedSignalEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *ExplainedSignalEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

type CompiledUserSignalsEntity struct {
	TargetFingerprint      string `protobuf:"bytes,1,opt,name=TargetFingerprint" json:"TargetFingerprint,omitempty"`
	Domain                 string `protobuf:"bytes,2,opt,name=Domain" json:"Domain,omitempty"`
	FollowedBySelf         bool   `protobuf:"varint,3,opt,name=FollowedBySelf" json:"FollowedBySelf,omitempty"`
	BlockedBySelf          bool   `protobuf:"varint,4,opt,name=BlockedBySelf" json:"BlockedBySelf,omitempty"`
	FollowerCount          int32  `protobuf:"varint,5,opt,name=FollowerCount" json:"FollowerCount,omitempty"`
	CanonicalName          string `protobuf:"bytes,6,opt,name=CanonicalName" json:"CanonicalName,omitempty"`
	CNameSourceFingerprint string `protobuf:"bytes,7,opt,name=CNameSourceFingerprint" json:"CNameSourceFingerprint,omitempty"`
	SelfPEFingerprint      string `protobuf:"bytes,8,opt,name=SelfPEFingerprint" json:"SelfPEFingerprint,omitempty"`
	SelfPECreation         int64  `protobuf:"varint,9,opt,name=SelfPECreation" json:"SelfPECreation,omitempty"`
	SelfPELastUpdate       int64  `protobuf:"varint,10,opt,name=SelfPELastUpdate" json:"SelfPELastUpdate,omitempty"`
	MadeModBySelf          bool   `protobuf:"varint,11,opt,name=MadeModBySelf" json:"MadeModBySelf,omitempty"`
	MadeNonModBySelf       bool   `protobuf:"varint,12,opt,name=MadeNonModBySelf" json:"MadeNonModBySelf,omitempty"`
	MadeModByDefault       bool   `protobuf:"varint,13,opt,name=MadeModByDefault" json:"MadeModByDefault,omitempty"`
	MadeModByNetwork       bool   `protobuf:"varint,14,opt,name=MadeModByNetwork" json:"MadeModByNetwork,omitempty"`
	MadeNonModByNetwork    bool   `protobuf:"varint,15,opt,name=MadeNonModByNetwork" json:"MadeNonModByNetwork,omitempty"`
}

func (m *CompiledUserSignalsEntity) Reset()                    { *m = CompiledUserSignalsEntity{} }
func (m *CompiledUserSignalsEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledUserSignalsEntity) ProtoMessage()               {}
func (*CompiledUserSignalsEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CompiledUserSignalsEntity) GetTargetFingerprint() string {
	if m != nil {
		return m.TargetFingerprint
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetFollowedBySelf() bool {
	if m != nil {
		return m.FollowedBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetBlockedBySelf() bool {
	if m != nil {
		return m.BlockedBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetFollowerCount() int32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *CompiledUserSignalsEntity) GetCanonicalName() string {
	if m != nil {
		return m.CanonicalName
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetCNameSourceFingerprint() string {
	if m != nil {
		return m.CNameSourceFingerprint
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetSelfPEFingerprint() string {
	if m != nil {
		return m.SelfPEFingerprint
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetSelfPECreation() int64 {
	if m != nil {
		return m.SelfPECreation
	}
	return 0
}

func (m *CompiledUserSignalsEntity) GetSelfPELastUpdate() int64 {
	if m != nil {
		return m.SelfPELastUpdate
	}
	return 0
}

func (m *CompiledUserSignalsEntity) GetMadeModBySelf() bool {
	if m != nil {
		return m.MadeModBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeNonModBySelf() bool {
	if m != nil {
		return m.MadeNonModBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeModByDefault() bool {
	if m != nil {
		return m.MadeModByDefault
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeModByNetwork() bool {
	if m != nil {
		return m.MadeModByNetwork
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeNonModByNetwork() bool {
	if m != nil {
		return m.MadeNonModByNetwork
	}
	return false
}

type AmbientBoardEntity struct {
	Fingerprint string `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	LastUpdate  int64  `protobuf:"varint,3,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	LastSeen    int64  `protobuf:"varint,4,opt,name=LastSeen" json:"LastSeen,omitempty"`
	Notify      bool   `protobuf:"varint,5,opt,name=Notify" json:"Notify,omitempty"`
}

func (m *AmbientBoardEntity) Reset()                    { *m = AmbientBoardEntity{} }
func (m *AmbientBoardEntity) String() string            { return proto.CompactTextString(m) }
func (*AmbientBoardEntity) ProtoMessage()               {}
func (*AmbientBoardEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AmbientBoardEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *AmbientBoardEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AmbientBoardEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *AmbientBoardEntity) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *AmbientBoardEntity) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

// This is the status of the backend and what it is doing
type BackendAmbientStatus struct {
	// ----------  Inbounds  ----------
	LastInboundConnTimestamp int64 `protobuf:"varint,1,opt,name=LastInboundConnTimestamp" json:"LastInboundConnTimestamp,omitempty"`
	InboundsCount15          int32 `protobuf:"varint,2,opt,name=InboundsCount15" json:"InboundsCount15,omitempty"`
	// ----------  Outbounds  ----------
	LastOutboundConnTimestamp   int64 `protobuf:"varint,3,opt,name=LastOutboundConnTimestamp" json:"LastOutboundConnTimestamp,omitempty"`
	OutboundsCount15            int32 `protobuf:"varint,4,opt,name=OutboundsCount15" json:"OutboundsCount15,omitempty"`
	LastOutboundDurationSeconds int32 `protobuf:"varint,5,opt,name=LastOutboundDurationSeconds" json:"LastOutboundDurationSeconds,omitempty"`
	// ----------  Misc  ----------
	LocalNodeExternalIP   string `protobuf:"bytes,6,opt,name=LocalNodeExternalIP" json:"LocalNodeExternalIP,omitempty"`
	LocalNodeExternalPort int32  `protobuf:"varint,7,opt,name=LocalNodeExternalPort" json:"LocalNodeExternalPort,omitempty"`
	UPNPStatus            string `protobuf:"bytes,8,opt,name=UPNPStatus" json:"UPNPStatus,omitempty"`
	// ----------  DATABASE  ----------
	DatabaseStatus            string `protobuf:"bytes,9,opt,name=DatabaseStatus" json:"DatabaseStatus,omitempty"`
	DbSizeMb                  int64  `protobuf:"varint,10,opt,name=DbSizeMb" json:"DbSizeMb,omitempty"`
	MaxDbSizeMb               int64  `protobuf:"varint,11,opt,name=MaxDbSizeMb" json:"MaxDbSizeMb,omitempty"`
	LastDbInsertTimestamp     int64  `protobuf:"varint,12,opt,name=LastDbInsertTimestamp" json:"LastDbInsertTimestamp,omitempty"`
	LastInsertDurationSeconds int32  `protobuf:"varint,13,opt,name=LastInsertDurationSeconds" json:"LastInsertDurationSeconds,omitempty"`
	// ----------  CACHING  ----------
	CachingStatus                      string `protobuf:"bytes,14,opt,name=CachingStatus" json:"CachingStatus,omitempty"`
	LastCacheGenerationTimestamp       int64  `protobuf:"varint,15,opt,name=LastCacheGenerationTimestamp" json:"LastCacheGenerationTimestamp,omitempty"`
	LastCacheGenerationDurationSeconds int32  `protobuf:"varint,16,opt,name=LastCacheGenerationDurationSeconds" json:"LastCacheGenerationDurationSeconds,omitempty"`
	// ----------  CONFIG LOCATION  ----------
	BackendConfigLocation string `protobuf:"bytes,17,opt,name=BackendConfigLocation" json:"BackendConfigLocation,omitempty"`
}

func (m *BackendAmbientStatus) Reset()                    { *m = BackendAmbientStatus{} }
func (m *BackendAmbientStatus) String() string            { return proto.CompactTextString(m) }
func (*BackendAmbientStatus) ProtoMessage()               {}
func (*BackendAmbientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BackendAmbientStatus) GetLastInboundConnTimestamp() int64 {
	if m != nil {
		return m.LastInboundConnTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetInboundsCount15() int32 {
	if m != nil {
		return m.InboundsCount15
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastOutboundConnTimestamp() int64 {
	if m != nil {
		return m.LastOutboundConnTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetOutboundsCount15() int32 {
	if m != nil {
		return m.OutboundsCount15
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastOutboundDurationSeconds() int32 {
	if m != nil {
		return m.LastOutboundDurationSeconds
	}
	return 0
}

func (m *BackendAmbientStatus) GetLocalNodeExternalIP() string {
	if m != nil {
		return m.LocalNodeExternalIP
	}
	return ""
}

func (m *BackendAmbientStatus) GetLocalNodeExternalPort() int32 {
	if m != nil {
		return m.LocalNodeExternalPort
	}
	return 0
}

func (m *BackendAmbientStatus) GetUPNPStatus() string {
	if m != nil {
		return m.UPNPStatus
	}
	return ""
}

func (m *BackendAmbientStatus) GetDatabaseStatus() string {
	if m != nil {
		return m.DatabaseStatus
	}
	return ""
}

func (m *BackendAmbientStatus) GetDbSizeMb() int64 {
	if m != nil {
		return m.DbSizeMb
	}
	return 0
}

func (m *BackendAmbientStatus) GetMaxDbSizeMb() int64 {
	if m != nil {
		return m.MaxDbSizeMb
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastDbInsertTimestamp() int64 {
	if m != nil {
		return m.LastDbInsertTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastInsertDurationSeconds() int32 {
	if m != nil {
		return m.LastInsertDurationSeconds
	}
	return 0
}

func (m *BackendAmbientStatus) GetCachingStatus() string {
	if m != nil {
		return m.CachingStatus
	}
	return ""
}

func (m *BackendAmbientStatus) GetLastCacheGenerationTimestamp() int64 {
	if m != nil {
		return m.LastCacheGenerationTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastCacheGenerationDurationSeconds() int32 {
	if m != nil {
		return m.LastCacheGenerationDurationSeconds
	}
	return 0
}

func (m *BackendAmbientStatus) GetBackendConfigLocation() string {
	if m != nil {
		return m.BackendConfigLocation
	}
	return ""
}

type FrontendAmbientStatus struct {
	RefresherStatus            string `protobuf:"bytes,1,opt,name=RefresherStatus" json:"RefresherStatus,omitempty"`
	LastRefreshTimestamp       int64  `protobuf:"varint,2,opt,name=LastRefreshTimestamp" json:"LastRefreshTimestamp,omitempty"`
	LastRefreshDurationSeconds int32  `protobuf:"varint,3,opt,name=LastRefreshDurationSeconds" json:"LastRefreshDurationSeconds,omitempty"`
	FrontendConfigLocation     string `protobuf:"bytes,4,opt,name=FrontendConfigLocation" json:"FrontendConfigLocation,omitempty"`
	SFWListDisabled            bool   `protobuf:"varint,5,opt,name=SFWListDisabled" json:"SFWListDisabled,omitempty"`
}

func (m *FrontendAmbientStatus) Reset()                    { *m = FrontendAmbientStatus{} }
func (m *FrontendAmbientStatus) String() string            { return proto.CompactTextString(m) }
func (*FrontendAmbientStatus) ProtoMessage()               {}
func (*FrontendAmbientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FrontendAmbientStatus) GetRefresherStatus() string {
	if m != nil {
		return m.RefresherStatus
	}
	return ""
}

func (m *FrontendAmbientStatus) GetLastRefreshTimestamp() int64 {
	if m != nil {
		return m.LastRefreshTimestamp
	}
	return 0
}

func (m *FrontendAmbientStatus) GetLastRefreshDurationSeconds() int32 {
	if m != nil {
		return m.LastRefreshDurationSeconds
	}
	return 0
}

func (m *FrontendAmbientStatus) GetFrontendConfigLocation() string {
	if m != nil {
		return m.FrontendConfigLocation
	}
	return ""
}

func (m *FrontendAmbientStatus) GetSFWListDisabled() bool {
	if m != nil {
		return m.SFWListDisabled
	}
	return false
}

type CompiledNotification struct {
	Type                    NotificationType      `protobuf:"varint,1,opt,name=Type,enum=feobjects.NotificationType" json:"Type,omitempty"`
	Text                    string                `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
	ResponsePosts           []string              `protobuf:"bytes,3,rep,name=ResponsePosts" json:"ResponsePosts,omitempty"`
	ParentThread            *CompiledThreadEntity `protobuf:"bytes,4,opt,name=ParentThread" json:"ParentThread,omitempty"`
	ParentPost              *CompiledPostEntity   `protobuf:"bytes,5,opt,name=ParentPost" json:"ParentPost,omitempty"`
	CreationTimestamp       int64                 `protobuf:"varint,6,opt,name=CreationTimestamp" json:"CreationTimestamp,omitempty"`
	NewestResponseTimestamp int64                 `protobuf:"varint,7,opt,name=NewestResponseTimestamp" json:"NewestResponseTimestamp,omitempty"`
	Read                    bool                  `protobuf:"varint,8,opt,name=Read" json:"Read,omitempty"`
}

func (m *CompiledNotification) Reset()                    { *m = CompiledNotification{} }
func (m *CompiledNotification) String() string            { return proto.CompactTextString(m) }
func (*CompiledNotification) ProtoMessage()               {}
func (*CompiledNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CompiledNotification) GetType() NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationType_UNKNOWN_NOTIFICATION_TYPE
}

func (m *CompiledNotification) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CompiledNotification) GetResponsePosts() []string {
	if m != nil {
		return m.ResponsePosts
	}
	return nil
}

func (m *CompiledNotification) GetParentThread() *CompiledThreadEntity {
	if m != nil {
		return m.ParentThread
	}
	return nil
}

func (m *CompiledNotification) GetParentPost() *CompiledPostEntity {
	if m != nil {
		return m.ParentPost
	}
	return nil
}

func (m *CompiledNotification) GetCreationTimestamp() int64 {
	if m != nil {
		return m.CreationTimestamp
	}
	return 0
}

func (m *CompiledNotification) GetNewestResponseTimestamp() int64 {
	if m != nil {
		return m.NewestResponseTimestamp
	}
	return 0
}

func (m *CompiledNotification) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

type ReportsTabEntry struct {
	Fingerprint   string                `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	BoardPayload  *CompiledBoardEntity  `protobuf:"bytes,2,opt,name=BoardPayload" json:"BoardPayload,omitempty"`
	ThreadPayload *CompiledThreadEntity `protobuf:"bytes,3,opt,name=ThreadPayload" json:"ThreadPayload,omitempty"`
	PostPayload   *CompiledPostEntity   `protobuf:"bytes,4,opt,name=PostPayload" json:"PostPayload,omitempty"`
	Timestamp     int64                 `protobuf:"varint,5,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *ReportsTabEntry) Reset()                    { *m = ReportsTabEntry{} }
func (m *ReportsTabEntry) String() string            { return proto.CompactTextString(m) }
func (*ReportsTabEntry) ProtoMessage()               {}
func (*ReportsTabEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReportsTabEntry) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *ReportsTabEntry) GetBoardPayload() *CompiledBoardEntity {
	if m != nil {
		return m.BoardPayload
	}
	return nil
}

func (m *ReportsTabEntry) GetThreadPayload() *CompiledThreadEntity {
	if m != nil {
		return m.ThreadPayload
	}
	return nil
}

func (m *ReportsTabEntry) GetPostPayload() *CompiledPostEntity {
	if m != nil {
		return m.PostPayload
	}
	return nil
}

func (m *ReportsTabEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*CompiledBoardEntity)(nil), "feobjects.CompiledBoardEntity")
	proto.RegisterType((*CompiledThreadEntity)(nil), "feobjects.CompiledThreadEntity")
	proto.RegisterType((*CompiledPostEntity)(nil), "feobjects.CompiledPostEntity")
	proto.RegisterType((*CompiledUserEntity)(nil), "feobjects.CompiledUserEntity")
	proto.RegisterType((*CompiledContentSignalsEntity)(nil), "feobjects.CompiledContentSignalsEntity")
	proto.RegisterType((*ExplainedSignalEntity)(nil), "feobjects.ExplainedSignalEntity")
	proto.RegisterType((*CompiledUserSignalsEntity)(nil), "feobjects.CompiledUserSignalsEntity")
	proto.RegisterType((*AmbientBoardEntity)(nil), "feobjects.AmbientBoardEntity")
	proto.RegisterType((*BackendAmbientStatus)(nil), "feobjects.BackendAmbientStatus")
	proto.RegisterType((*FrontendAmbientStatus)(nil), "feobjects.FrontendAmbientStatus")
	proto.RegisterType((*CompiledNotification)(nil), "feobjects.CompiledNotification")
	proto.RegisterType((*ReportsTabEntry)(nil), "feobjects.ReportsTabEntry")
	proto.RegisterEnum("feobjects.NotificationType", NotificationType_name, NotificationType_value)
}

func init() { proto.RegisterFile("feobjects/feobjects.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1805 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4b, 0x73, 0x1b, 0xc7,
	0x11, 0x0e, 0x88, 0x07, 0x81, 0x01, 0xf8, 0x1a, 0x3e, 0xb4, 0x94, 0x28, 0x05, 0x85, 0x52, 0x25,
	0x28, 0x55, 0x22, 0x25, 0x54, 0x92, 0x4a, 0x54, 0x89, 0x12, 0xe2, 0xc1, 0x04, 0x15, 0x12, 0x40,
	0x2d, 0xc0, 0xa8, 0x94, 0x0b, 0x6b, 0x81, 0x1d, 0x92, 0x6b, 0x82, 0x33, 0xa8, 0xdd, 0x81, 0x48,
	0xf8, 0xe6, 0xf2, 0xc1, 0x57, 0xfb, 0xe4, 0x8b, 0xed, 0x3f, 0xe5, 0xab, 0x7f, 0x89, 0x4f, 0xae,
	0x9e, 0x99, 0xdd, 0x9d, 0x7d, 0x00, 0xa2, 0x6c, 0x1f, 0x7d, 0x9b, 0xf9, 0xba, 0x67, 0x76, 0xba,
	0xfb, 0xeb, 0xee, 0x99, 0x45, 0xfb, 0x17, 0x84, 0x8d, 0x3e, 0x22, 0x63, 0xee, 0xbd, 0x08, 0x46,
	0xcf, 0xa7, 0x2e, 0xe3, 0x0c, 0x97, 0x02, 0xa0, 0xf6, 0x79, 0x1e, 0x6d, 0x37, 0xd9, 0xcd, 0xd4,
	0x99, 0x10, 0xbb, 0xc1, 0x2c, 0xd7, 0x6e, 0x53, 0xee, 0xf0, 0x39, 0xae, 0xa2, 0xf2, 0xb1, 0x43,
	0x2f, 0x89, 0x3b, 0x75, 0x1d, 0xca, 0x8d, 0x4c, 0x35, 0x53, 0x2f, 0x99, 0x3a, 0x04, 0x1a, 0x03,
	0x32, 0xb9, 0x68, 0xba, 0xc4, 0xe2, 0xc4, 0x36, 0x56, 0xaa, 0x99, 0x7a, 0xd1, 0xd4, 0x21, 0x8c,
	0x51, 0xae, 0x6b, 0xdd, 0x10, 0x23, 0x2b, 0x16, 0x8b, 0x31, 0xac, 0x6a, 0x11, 0x6f, 0xec, 0x3a,
	0x53, 0xee, 0x30, 0x6a, 0xe4, 0xe4, 0xbe, 0x1a, 0x84, 0xcf, 0xd1, 0x9e, 0x7f, 0xa0, 0x26, 0xa3,
	0x9c, 0x50, 0x3e, 0x70, 0x2e, 0xa9, 0x35, 0xf1, 0x8c, 0x7c, 0x35, 0x53, 0x2f, 0x1f, 0xfe, 0xf6,
	0x79, 0x68, 0x4e, 0xba, 0xa2, 0x34, 0xc1, 0x5c, 0xb0, 0x0d, 0x7e, 0x89, 0xf2, 0xbd, 0x5b, 0x4a,
	0x5c, 0xa3, 0x20, 0xf6, 0x7b, 0x9c, 0xb2, 0xdf, 0x99, 0x47, 0x5c, 0xb5, 0x8b, 0xd4, 0x85, 0x73,
	0x0b, 0xf7, 0x88, 0x99, 0x67, 0xac, 0x56, 0xb3, 0x70, 0x6e, 0x0d, 0xc2, 0x0f, 0x51, 0x51, 0x18,
	0x0e, 0x66, 0x15, 0xab, 0x99, 0x7a, 0xd6, 0x0c, 0xe6, 0xf8, 0x09, 0x42, 0x27, 0x96, 0xc7, 0xcf,
	0xa6, 0xb6, 0xc5, 0x89, 0x51, 0x12, 0x52, 0x0d, 0x01, 0x4f, 0x9d, 0x12, 0x6e, 0x19, 0x48, 0x7a,
	0x0a, 0xc6, 0xb8, 0x89, 0x2a, 0xcd, 0x2b, 0x67, 0x62, 0x0f, 0xaf, 0x5c, 0x62, 0xd9, 0x9e, 0x51,
	0xae, 0x66, 0xeb, 0xe5, 0xc3, 0x5f, 0xa7, 0x9c, 0x56, 0x6a, 0xa8, 0xf3, 0x46, 0x16, 0xe1, 0x1a,
	0xaa, 0xa8, 0x61, 0x93, 0xcd, 0x28, 0x37, 0x2a, 0xd5, 0x4c, 0x3d, 0x6f, 0x46, 0x30, 0x7c, 0x80,
	0x4a, 0x60, 0xaf, 0x54, 0x58, 0x13, 0x0a, 0x21, 0x00, 0x47, 0x1f, 0xcc, 0x46, 0x10, 0x9e, 0x11,
	0xb1, 0x8d, 0x75, 0x11, 0x65, 0x0d, 0xc1, 0x7b, 0xa8, 0xd0, 0x65, 0xdc, 0xb9, 0x98, 0x1b, 0x1b,
	0x42, 0xa6, 0x66, 0xe0, 0x0e, 0x30, 0x70, 0x40, 0x08, 0x35, 0x36, 0xa5, 0x3b, 0xfc, 0x39, 0x7c,
	0x71, 0x70, 0xfc, 0xe6, 0xc4, 0xf1, 0x80, 0x38, 0x5b, 0x62, 0x59, 0x08, 0xd4, 0x3e, 0xcd, 0xa1,
	0x9d, 0x34, 0xd3, 0xee, 0xc1, 0xc9, 0x1d, 0x94, 0x17, 0x21, 0x11, 0x6c, 0x2c, 0x99, 0x72, 0x12,
	0x67, 0x6a, 0x76, 0x31, 0x53, 0x73, 0x1a, 0x53, 0x31, 0xca, 0x35, 0x98, 0x3d, 0x17, 0xac, 0x2b,
	0x99, 0x62, 0x0c, 0xd8, 0x89, 0x43, 0xaf, 0x05, 0x73, 0x4a, 0xa6, 0x18, 0x2f, 0xe1, 0xeb, 0xea,
	0xcf, 0xcc, 0xd7, 0xe2, 0x07, 0xf0, 0x55, 0x67, 0x63, 0x69, 0x29, 0x1b, 0xd1, 0x42, 0x36, 0x96,
	0x35, 0x36, 0xfe, 0x0d, 0x15, 0x05, 0xb1, 0x5c, 0x42, 0x8d, 0x8a, 0x60, 0x62, 0xda, 0x39, 0xfa,
	0xcc, 0xe3, 0xea, 0x1c, 0x81, 0x3a, 0x7c, 0x0e, 0x70, 0x4f, 0x27, 0x98, 0x86, 0x40, 0xd0, 0x06,
	0x63, 0xe6, 0x12, 0x41, 0xae, 0x8c, 0x29, 0x27, 0xb5, 0x6f, 0xb3, 0x08, 0x27, 0xb7, 0xfd, 0xd1,
	0x1c, 0xd8, 0x43, 0x05, 0xc9, 0x25, 0x55, 0x8d, 0xd4, 0x0c, 0xf0, 0xbe, 0xe5, 0x12, 0xca, 0x55,
	0xec, 0xd5, 0x2c, 0xce, 0x99, 0x7c, 0x2a, 0x67, 0x04, 0x3f, 0x0a, 0x1a, 0x3f, 0x7e, 0xe1, 0xc2,
	0x72, 0x2e, 0xd4, 0xbe, 0x5b, 0x09, 0xa3, 0x1a, 0x1e, 0xf4, 0x1e, 0x51, 0x7d, 0x86, 0x36, 0xbb,
	0x8c, 0x36, 0x2d, 0xca, 0xa8, 0x33, 0xb6, 0x26, 0x22, 0x5b, 0x65, 0x80, 0x13, 0x78, 0xc4, 0xde,
	0xec, 0x52, 0x7b, 0x73, 0x09, 0x7b, 0x9f, 0xa2, 0x35, 0x98, 0x99, 0xe4, 0xc2, 0x25, 0xde, 0x95,
	0x8a, 0x7c, 0xd6, 0x8c, 0x82, 0xf8, 0x7f, 0x61, 0xd3, 0x04, 0x2b, 0xfc, 0x20, 0xcb, 0x86, 0xf2,
	0x74, 0x41, 0x50, 0xa2, 0x11, 0x4e, 0xdb, 0x00, 0xd8, 0xd8, 0xbe, 0x9b, 0x3a, 0xee, 0x5c, 0xf0,
	0x25, 0x6b, 0xaa, 0x19, 0x44, 0xa1, 0x43, 0x2f, 0x98, 0x88, 0x7a, 0xc9, 0x14, 0xe3, 0x20, 0x32,
	0xa5, 0x30, 0x32, 0xb5, 0xaf, 0x56, 0xd1, 0xc1, 0x32, 0x5e, 0xe1, 0xdf, 0xa1, 0xad, 0xa1, 0xe5,
	0x5e, 0x12, 0x9e, 0x74, 0x77, 0x52, 0x80, 0x0d, 0xb4, 0x7a, 0x36, 0x7d, 0xc7, 0x38, 0xf1, 0x84,
	0xaf, 0xf3, 0xa6, 0x3f, 0x85, 0x0a, 0xde, 0x62, 0xb7, 0x54, 0xca, 0xb2, 0xb2, 0x67, 0x04, 0x80,
	0x9f, 0x3c, 0x52, 0xd9, 0x16, 0x5e, 0x56, 0xc9, 0xa3, 0x20, 0x70, 0x33, 0x4c, 0xfd, 0x25, 0x7e,
	0x82, 0x45, 0x41, 0x5c, 0x47, 0x1b, 0x00, 0x1c, 0x0d, 0x5b, 0x41, 0x3c, 0x0b, 0xc2, 0x2f, 0x71,
	0x18, 0xec, 0x52, 0x90, 0x16, 0x5d, 0xe9, 0xc3, 0xa4, 0x00, 0x3f, 0x47, 0x58, 0x81, 0xba, 0x1b,
	0xa4, 0x73, 0x53, 0x24, 0xf8, 0x15, 0x5a, 0x35, 0xc9, 0x94, 0xb9, 0xdc, 0x33, 0x4a, 0x82, 0xef,
	0x55, 0x2d, 0xc4, 0xed, 0xbb, 0xe9, 0xc4, 0x72, 0x28, 0xb1, 0xa5, 0xa7, 0x55, 0x78, 0xfd, 0x05,
	0xf8, 0x35, 0x2a, 0x9d, 0x32, 0xbb, 0x31, 0x61, 0xe3, 0x6b, 0xbf, 0x87, 0xbf, 0x7f, 0x75, 0xb8,
	0x04, 0xb7, 0x50, 0xe5, 0x94, 0xd9, 0x47, 0xd3, 0xa9, 0xcb, 0xde, 0x01, 0xc7, 0x2a, 0xf7, 0xdc,
	0x22, 0xb2, 0x4a, 0x14, 0xc5, 0xf9, 0x29, 0xb3, 0x45, 0xf9, 0x2d, 0x9a, 0x72, 0x02, 0x49, 0xd5,
	0x98, 0x1f, 0xb3, 0xc9, 0x84, 0xdd, 0x12, 0xbb, 0x4f, 0x5c, 0x8f, 0x51, 0xd5, 0xe1, 0x13, 0x38,
	0xc4, 0xa2, 0x31, 0x17, 0x67, 0x0a, 0x54, 0x65, 0xc3, 0x8f, 0xc3, 0xa2, 0x30, 0xce, 0x7b, 0x7d,
	0xd1, 0xf5, 0x8b, 0xa6, 0x18, 0x43, 0xda, 0xf9, 0x26, 0x05, 0x2d, 0x5f, 0x43, 0x80, 0x31, 0xc1,
	0x79, 0x89, 0x6d, 0x60, 0xc9, 0x18, 0x0d, 0x4a, 0x26, 0xe6, 0x76, 0x5a, 0x62, 0x2a, 0xc6, 0xe8,
	0x7b, 0xed, 0xc8, 0x53, 0xc6, 0x60, 0xfc, 0x1b, 0xb4, 0xae, 0x20, 0xff, 0x54, 0xbb, 0x42, 0x31,
	0x86, 0x6a, 0x7a, 0x9d, 0x4b, 0xca, 0x5c, 0x62, 0x1b, 0x7b, 0x11, 0x3d, 0x85, 0xc2, 0x4d, 0x0b,
	0x10, 0x19, 0x76, 0x62, 0x1b, 0x0f, 0x84, 0x56, 0x04, 0xab, 0x7d, 0x96, 0x41, 0xbb, 0xa9, 0xd1,
	0x82, 0x92, 0x35, 0x60, 0x33, 0x77, 0x4c, 0x8e, 0xa7, 0x2a, 0x1d, 0x83, 0x39, 0x14, 0x05, 0x93,
	0x58, 0xe0, 0x70, 0x59, 0xf0, 0xd4, 0xec, 0xa7, 0x94, 0xb9, 0xda, 0x17, 0x79, 0xb4, 0xbf, 0xb0,
	0x36, 0x7d, 0x60, 0x95, 0xd8, 0x43, 0x85, 0x16, 0xbb, 0xb1, 0x9c, 0xe0, 0x7c, 0x72, 0x06, 0x9e,
	0xf3, 0x39, 0xd4, 0x98, 0x83, 0x1f, 0xd4, 0xcd, 0x2b, 0x86, 0x42, 0x64, 0x95, 0xb3, 0x95, 0x9a,
	0xac, 0x17, 0x51, 0x10, 0xb4, 0xd4, 0x3a, 0x75, 0x53, 0xcd, 0x8b, 0xaa, 0x13, 0x05, 0x41, 0x2b,
	0xda, 0x23, 0x64, 0x77, 0x8e, 0x82, 0xf8, 0x2f, 0x68, 0xaf, 0x09, 0x03, 0xe5, 0x62, 0xcd, 0xc8,
	0x55, 0xa1, 0xbe, 0x40, 0xea, 0x57, 0x99, 0x7e, 0x3b, 0x59, 0x36, 0x92, 0x02, 0x9f, 0x39, 0xfd,
	0x76, 0xac, 0xf9, 0xc6, 0x50, 0xc8, 0x42, 0x89, 0x24, 0x1a, 0x71, 0x02, 0x07, 0xfb, 0x4e, 0x2d,
	0x9b, 0x00, 0x3f, 0xa5, 0xaf, 0xca, 0xd2, 0x57, 0x11, 0x10, 0x76, 0x04, 0xa0, 0xcb, 0x68, 0xa8,
	0x58, 0x91, 0x79, 0x1d, 0xc7, 0x7d, 0x5d, 0x01, 0xb4, 0xc8, 0x85, 0x35, 0x9b, 0x70, 0x55, 0x24,
	0x12, 0x78, 0x44, 0xb7, 0x4b, 0xf8, 0x2d, 0x73, 0xaf, 0xfd, 0x7a, 0x11, 0xc7, 0xf1, 0x1f, 0xd0,
	0xb6, 0xfe, 0x2d, 0x5f, 0x5d, 0xd6, 0x8c, 0x34, 0x51, 0xed, 0x9b, 0x0c, 0xc2, 0x47, 0x37, 0x23,
	0x87, 0x50, 0xfe, 0x61, 0x2f, 0x51, 0xff, 0xf6, 0xbe, 0xa2, 0xdd, 0xde, 0xa3, 0x09, 0x90, 0x4d,
	0xf4, 0x79, 0xfd, 0x79, 0x92, 0x8b, 0x3d, 0x4f, 0xc2, 0x27, 0x4d, 0x5e, 0x7f, 0xd2, 0xd4, 0xbe,
	0x2f, 0xa0, 0x9d, 0x86, 0x35, 0xbe, 0x26, 0xd4, 0x56, 0xe7, 0x1c, 0x70, 0x8b, 0xcf, 0x3c, 0xfc,
	0x0a, 0x19, 0xb0, 0xb8, 0x43, 0x47, 0x6c, 0x46, 0xa1, 0xf1, 0xd2, 0xa1, 0x73, 0x43, 0x3c, 0x6e,
	0xdd, 0xc8, 0x6c, 0xce, 0x9a, 0x0b, 0xe5, 0x50, 0xb1, 0x14, 0x2e, 0xaf, 0xc3, 0x7f, 0xfc, 0xb3,
	0xea, 0xb5, 0x71, 0x18, 0xff, 0x1d, 0xed, 0xc3, 0x2e, 0xbd, 0x19, 0x4f, 0xf9, 0x8c, 0xb4, 0x70,
	0xb1, 0x02, 0xc4, 0xce, 0x17, 0x04, 0x1f, 0xca, 0x89, 0x0f, 0x25, 0x70, 0xfc, 0x2f, 0xf4, 0x48,
	0xdf, 0xa8, 0x35, 0x73, 0x05, 0x53, 0x07, 0x64, 0xcc, 0xa8, 0xed, 0xa9, 0xcc, 0x5b, 0xa6, 0x02,
	0xd1, 0x3f, 0x61, 0x90, 0x6e, 0xcc, 0x26, 0xed, 0x3b, 0x4e, 0x5c, 0x6a, 0x4d, 0x3a, 0x7d, 0x95,
	0x8d, 0x69, 0x22, 0xfc, 0x27, 0xb4, 0x9b, 0x80, 0xfb, 0xcc, 0x95, 0x29, 0x99, 0x37, 0xd3, 0x85,
	0x10, 0xe6, 0xb3, 0x7e, 0xb7, 0x2f, 0xe3, 0xa0, 0x52, 0x51, 0x43, 0x20, 0x07, 0x5b, 0x16, 0xb7,
	0x46, 0x96, 0x47, 0x94, 0x8e, 0xbc, 0x2e, 0xc5, 0x50, 0xa0, 0x43, 0x6b, 0x34, 0x70, 0x3e, 0x26,
	0xa7, 0x23, 0x95, 0x7b, 0xc1, 0x5c, 0xf4, 0x26, 0xeb, 0x2e, 0x10, 0x97, 0x85, 0x58, 0x87, 0xc4,
	0xd9, 0x2d, 0x8f, 0xb7, 0x46, 0x1d, 0xea, 0x11, 0x97, 0x87, 0x51, 0xa9, 0x08, 0xdd, 0x74, 0xa1,
	0x1f, 0x4f, 0x09, 0xc7, 0x7d, 0x2c, 0x9f, 0x49, 0x8b, 0x15, 0x64, 0xa5, 0x1b, 0x5f, 0x39, 0xf4,
	0x52, 0x19, 0xb6, 0xee, 0x57, 0x3a, 0x0d, 0xc4, 0x0d, 0x74, 0x00, 0x5b, 0x00, 0x48, 0xfe, 0x4d,
	0x28, 0x91, 0x7b, 0x84, 0x07, 0xdc, 0x10, 0x07, 0x5c, 0xaa, 0x83, 0xbb, 0xa8, 0x96, 0x22, 0x8f,
	0x1f, 0x78, 0x53, 0x1c, 0xf8, 0x1e, 0x9a, 0xe0, 0x2d, 0x95, 0x45, 0x4d, 0x46, 0x2f, 0x9c, 0x4b,
	0x88, 0xac, 0x28, 0x8f, 0x5b, 0xc2, 0x82, 0x74, 0x61, 0xed, 0xcb, 0x15, 0xb4, 0x7b, 0xec, 0x8a,
	0x3b, 0x6d, 0x2c, 0xfb, 0xea, 0x68, 0xc3, 0xbf, 0x00, 0xb8, 0xca, 0x17, 0xb2, 0x48, 0xc4, 0x61,
	0x7c, 0x88, 0x76, 0xb4, 0xeb, 0x42, 0xe8, 0x85, 0x15, 0xe1, 0x85, 0x54, 0x19, 0x7e, 0x8d, 0x1e,
	0x6a, 0x78, 0xdc, 0x6a, 0x79, 0xf5, 0x5d, 0xa2, 0x01, 0xbd, 0xc6, 0x3f, 0x76, 0xcc, 0x5c, 0xf9,
	0xe0, 0x5c, 0x20, 0x15, 0x37, 0x19, 0xf9, 0x4b, 0xa4, 0xe5, 0x78, 0xd6, 0x68, 0x12, 0xdc, 0x91,
	0xe3, 0x70, 0xed, 0x93, 0x6c, 0xf8, 0xbf, 0x44, 0x54, 0x2a, 0x47, 0x6d, 0xf1, 0x02, 0xe5, 0x86,
	0xf3, 0x29, 0x11, 0xde, 0x58, 0x3f, 0x7c, 0xa4, 0x5d, 0x19, 0x75, 0x35, 0x50, 0x31, 0x85, 0x22,
	0x14, 0xd2, 0x21, 0xb9, 0xe3, 0x7e, 0x21, 0x85, 0x31, 0xf0, 0xcc, 0x24, 0xde, 0x94, 0x51, 0x8f,
	0x88, 0x37, 0xbb, 0x91, 0x15, 0xbf, 0xbe, 0xa2, 0x20, 0x6e, 0xa2, 0x8a, 0x7c, 0x38, 0xab, 0x47,
	0x76, 0x4e, 0xbc, 0x84, 0xde, 0xff, 0xb3, 0x4a, 0x5f, 0x84, 0xff, 0x81, 0x90, 0x9c, 0xc3, 0x9e,
	0xea, 0x6f, 0xdf, 0x7b, 0x5e, 0x96, 0xda, 0x02, 0xe8, 0xce, 0x7e, 0x4f, 0x0d, 0x43, 0x2b, 0xdf,
	0x0b, 0x49, 0x01, 0xfe, 0x2b, 0x7a, 0xd0, 0x25, 0xb7, 0x04, 0xe2, 0x26, 0x0d, 0x09, 0xd7, 0xc8,
	0x77, 0xc3, 0x22, 0x31, 0x78, 0xc9, 0x04, 0x1b, 0x8b, 0xf2, 0x7e, 0x0b, 0xe3, 0xda, 0xd7, 0x2b,
	0x40, 0x42, 0x71, 0xe3, 0x1f, 0x5a, 0xa3, 0x36, 0xe5, 0xee, 0x7d, 0x1a, 0x57, 0x03, 0x55, 0x44,
	0xa7, 0xeb, 0x5b, 0xf3, 0x09, 0xb3, 0xe4, 0x1f, 0x8b, 0xf2, 0xe1, 0x93, 0x14, 0x93, 0xb5, 0x86,
	0x68, 0x46, 0xd6, 0xe0, 0x36, 0x5a, 0x93, 0xee, 0xf3, 0x37, 0xc9, 0xde, 0xcf, 0xf5, 0xd1, 0x55,
	0xf8, 0x9f, 0xa8, 0x0c, 0x4e, 0xf4, 0x37, 0xc9, 0xdd, 0xc7, 0xf9, 0xfa, 0x0a, 0x78, 0x11, 0x86,
	0x1e, 0x94, 0x8f, 0xe6, 0x10, 0x78, 0xf6, 0x16, 0x9e, 0xef, 0x51, 0xce, 0xe1, 0xc7, 0x68, 0xff,
	0xac, 0xfb, 0xdf, 0x6e, 0xef, 0x4d, 0xf7, 0xbc, 0xdb, 0x1b, 0x76, 0x8e, 0x3b, 0xcd, 0xa3, 0x61,
	0xa7, 0xd7, 0x3d, 0x1f, 0xbe, 0xed, 0xb7, 0x37, 0x7f, 0x85, 0xb7, 0xd1, 0x86, 0xd9, 0xee, 0x9f,
	0xbc, 0x3d, 0x1f, 0xf6, 0xce, 0x87, 0xff, 0x31, 0xdb, 0x47, 0xad, 0xcd, 0x0c, 0xde, 0x42, 0x6b,
	0x01, 0xd8, 0xef, 0x0d, 0x86, 0x9b, 0x2b, 0x8d, 0x27, 0xff, 0x3f, 0xb0, 0x08, 0xbf, 0x22, 0xee,
	0xef, 0xc7, 0xcc, 0x25, 0x2f, 0xc4, 0x1f, 0x6e, 0xed, 0x97, 0xf7, 0xa8, 0x20, 0x90, 0x97, 0x3f,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x57, 0x6e, 0xfb, 0x10, 0x17, 0x00, 0x00,
}
