// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clapi/clapi.proto

/*
Package clapi is a generated protocol buffer package.

It is generated from these files:
	clapi/clapi.proto

It has these top-level messages:
	FEReadyRequest
	FEReadyResponse
	AmbientsRequest
	AmbientsResponse
	BackendAmbientStatus
	FrontendAmbientStatus
	InflightStatus
	InflightBoard
	InflightThread
	InflightPost
	InflightVote
	InflightKey
	InflightTruststate
	Inflights
	AmbientStatusPayload
	AmbientStatusResponse
	AmbientLocalUserEntityPayload
	AmbientLocalUserEntityResponse
*/
package clapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import feobjects "aether-core/protos/feobjects"
import structprotos "aether-core/protos/mimapi"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FEReadyRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Port    int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *FEReadyRequest) Reset()                    { *m = FEReadyRequest{} }
func (m *FEReadyRequest) String() string            { return proto.CompactTextString(m) }
func (*FEReadyRequest) ProtoMessage()               {}
func (*FEReadyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FEReadyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FEReadyRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type FEReadyResponse struct {
}

func (m *FEReadyResponse) Reset()                    { *m = FEReadyResponse{} }
func (m *FEReadyResponse) String() string            { return proto.CompactTextString(m) }
func (*FEReadyResponse) ProtoMessage()               {}
func (*FEReadyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// This delivers the updated ambients to the client.
type AmbientsRequest struct {
	Boards []*feobjects.AmbientBoardEntity `protobuf:"bytes,1,rep,name=Boards" json:"Boards,omitempty"`
}

func (m *AmbientsRequest) Reset()                    { *m = AmbientsRequest{} }
func (m *AmbientsRequest) String() string            { return proto.CompactTextString(m) }
func (*AmbientsRequest) ProtoMessage()               {}
func (*AmbientsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AmbientsRequest) GetBoards() []*feobjects.AmbientBoardEntity {
	if m != nil {
		return m.Boards
	}
	return nil
}

type AmbientsResponse struct {
}

func (m *AmbientsResponse) Reset()                    { *m = AmbientsResponse{} }
func (m *AmbientsResponse) String() string            { return proto.CompactTextString(m) }
func (*AmbientsResponse) ProtoMessage()               {}
func (*AmbientsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// This is the status of the backend and what it is doing
type BackendAmbientStatus struct {
}

func (m *BackendAmbientStatus) Reset()                    { *m = BackendAmbientStatus{} }
func (m *BackendAmbientStatus) String() string            { return proto.CompactTextString(m) }
func (*BackendAmbientStatus) ProtoMessage()               {}
func (*BackendAmbientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// General status of the frontend
type FrontendAmbientStatus struct {
}

func (m *FrontendAmbientStatus) Reset()                    { *m = FrontendAmbientStatus{} }
func (m *FrontendAmbientStatus) String() string            { return proto.CompactTextString(m) }
func (*FrontendAmbientStatus) ProtoMessage()               {}
func (*FrontendAmbientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type InflightStatus struct {
	CompletionPercent   int32  `protobuf:"varint,1,opt,name=CompletionPercent" json:"CompletionPercent,omitempty"`
	StatusText          string `protobuf:"bytes,2,opt,name=StatusText" json:"StatusText,omitempty"`
	RequestedTimestamp  int64  `protobuf:"varint,4,opt,name=RequestedTimestamp" json:"RequestedTimestamp,omitempty"`
	LastActionTimestamp int64  `protobuf:"varint,5,opt,name=LastActionTimestamp" json:"LastActionTimestamp,omitempty"`
	EventType           string `protobuf:"bytes,6,opt,name=EventType" json:"EventType,omitempty"`
}

func (m *InflightStatus) Reset()                    { *m = InflightStatus{} }
func (m *InflightStatus) String() string            { return proto.CompactTextString(m) }
func (*InflightStatus) ProtoMessage()               {}
func (*InflightStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InflightStatus) GetCompletionPercent() int32 {
	if m != nil {
		return m.CompletionPercent
	}
	return 0
}

func (m *InflightStatus) GetStatusText() string {
	if m != nil {
		return m.StatusText
	}
	return ""
}

func (m *InflightStatus) GetRequestedTimestamp() int64 {
	if m != nil {
		return m.RequestedTimestamp
	}
	return 0
}

func (m *InflightStatus) GetLastActionTimestamp() int64 {
	if m != nil {
		return m.LastActionTimestamp
	}
	return 0
}

func (m *InflightStatus) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type InflightBoard struct {
	Status *InflightStatus     `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Entity *structprotos.Board `protobuf:"bytes,2,opt,name=Entity" json:"Entity,omitempty"`
}

func (m *InflightBoard) Reset()                    { *m = InflightBoard{} }
func (m *InflightBoard) String() string            { return proto.CompactTextString(m) }
func (*InflightBoard) ProtoMessage()               {}
func (*InflightBoard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InflightBoard) GetStatus() *InflightStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InflightBoard) GetEntity() *structprotos.Board {
	if m != nil {
		return m.Entity
	}
	return nil
}

type InflightThread struct {
	Status *InflightStatus      `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Entity *structprotos.Thread `protobuf:"bytes,2,opt,name=Entity" json:"Entity,omitempty"`
}

func (m *InflightThread) Reset()                    { *m = InflightThread{} }
func (m *InflightThread) String() string            { return proto.CompactTextString(m) }
func (*InflightThread) ProtoMessage()               {}
func (*InflightThread) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *InflightThread) GetStatus() *InflightStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InflightThread) GetEntity() *structprotos.Thread {
	if m != nil {
		return m.Entity
	}
	return nil
}

type InflightPost struct {
	Status *InflightStatus    `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Entity *structprotos.Post `protobuf:"bytes,2,opt,name=Entity" json:"Entity,omitempty"`
}

func (m *InflightPost) Reset()                    { *m = InflightPost{} }
func (m *InflightPost) String() string            { return proto.CompactTextString(m) }
func (*InflightPost) ProtoMessage()               {}
func (*InflightPost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InflightPost) GetStatus() *InflightStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InflightPost) GetEntity() *structprotos.Post {
	if m != nil {
		return m.Entity
	}
	return nil
}

type InflightVote struct {
	Status *InflightStatus    `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Entity *structprotos.Vote `protobuf:"bytes,2,opt,name=Entity" json:"Entity,omitempty"`
}

func (m *InflightVote) Reset()                    { *m = InflightVote{} }
func (m *InflightVote) String() string            { return proto.CompactTextString(m) }
func (*InflightVote) ProtoMessage()               {}
func (*InflightVote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *InflightVote) GetStatus() *InflightStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InflightVote) GetEntity() *structprotos.Vote {
	if m != nil {
		return m.Entity
	}
	return nil
}

type InflightKey struct {
	Status *InflightStatus   `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Entity *structprotos.Key `protobuf:"bytes,2,opt,name=Entity" json:"Entity,omitempty"`
}

func (m *InflightKey) Reset()                    { *m = InflightKey{} }
func (m *InflightKey) String() string            { return proto.CompactTextString(m) }
func (*InflightKey) ProtoMessage()               {}
func (*InflightKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *InflightKey) GetStatus() *InflightStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InflightKey) GetEntity() *structprotos.Key {
	if m != nil {
		return m.Entity
	}
	return nil
}

type InflightTruststate struct {
	Status *InflightStatus          `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	Entity *structprotos.Truststate `protobuf:"bytes,2,opt,name=Entity" json:"Entity,omitempty"`
}

func (m *InflightTruststate) Reset()                    { *m = InflightTruststate{} }
func (m *InflightTruststate) String() string            { return proto.CompactTextString(m) }
func (*InflightTruststate) ProtoMessage()               {}
func (*InflightTruststate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *InflightTruststate) GetStatus() *InflightStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InflightTruststate) GetEntity() *structprotos.Truststate {
	if m != nil {
		return m.Entity
	}
	return nil
}

// The objects currently being processed.
type Inflights struct {
	Boards      []*InflightBoard      `protobuf:"bytes,1,rep,name=Boards" json:"Boards,omitempty"`
	Threads     []*InflightThread     `protobuf:"bytes,2,rep,name=Threads" json:"Threads,omitempty"`
	Posts       []*InflightPost       `protobuf:"bytes,3,rep,name=Posts" json:"Posts,omitempty"`
	Votes       []*InflightVote       `protobuf:"bytes,4,rep,name=Votes" json:"Votes,omitempty"`
	Keys        []*InflightKey        `protobuf:"bytes,5,rep,name=Keys" json:"Keys,omitempty"`
	Truststates []*InflightTruststate `protobuf:"bytes,6,rep,name=Truststates" json:"Truststates,omitempty"`
}

func (m *Inflights) Reset()                    { *m = Inflights{} }
func (m *Inflights) String() string            { return proto.CompactTextString(m) }
func (*Inflights) ProtoMessage()               {}
func (*Inflights) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Inflights) GetBoards() []*InflightBoard {
	if m != nil {
		return m.Boards
	}
	return nil
}

func (m *Inflights) GetThreads() []*InflightThread {
	if m != nil {
		return m.Threads
	}
	return nil
}

func (m *Inflights) GetPosts() []*InflightPost {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *Inflights) GetVotes() []*InflightVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Inflights) GetKeys() []*InflightKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Inflights) GetTruststates() []*InflightTruststate {
	if m != nil {
		return m.Truststates
	}
	return nil
}

type AmbientStatusPayload struct {
	// Health data from the backend, only provided to its admin frontend
	BackendAmbientStatus *BackendAmbientStatus `protobuf:"bytes,1,opt,name=BackendAmbientStatus" json:"BackendAmbientStatus,omitempty"`
	// Health data from the frontend
	FrontendAmbientStatus *FrontendAmbientStatus `protobuf:"bytes,2,opt,name=FrontendAmbientStatus" json:"FrontendAmbientStatus,omitempty"`
	// Lisf ot items currently being processed
	Inflights *Inflights `protobuf:"bytes,3,opt,name=Inflights" json:"Inflights,omitempty"`
}

func (m *AmbientStatusPayload) Reset()                    { *m = AmbientStatusPayload{} }
func (m *AmbientStatusPayload) String() string            { return proto.CompactTextString(m) }
func (*AmbientStatusPayload) ProtoMessage()               {}
func (*AmbientStatusPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AmbientStatusPayload) GetBackendAmbientStatus() *BackendAmbientStatus {
	if m != nil {
		return m.BackendAmbientStatus
	}
	return nil
}

func (m *AmbientStatusPayload) GetFrontendAmbientStatus() *FrontendAmbientStatus {
	if m != nil {
		return m.FrontendAmbientStatus
	}
	return nil
}

func (m *AmbientStatusPayload) GetInflights() *Inflights {
	if m != nil {
		return m.Inflights
	}
	return nil
}

type AmbientStatusResponse struct {
}

func (m *AmbientStatusResponse) Reset()                    { *m = AmbientStatusResponse{} }
func (m *AmbientStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*AmbientStatusResponse) ProtoMessage()               {}
func (*AmbientStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type AmbientLocalUserEntityPayload struct {
	LocalUserExists bool                          `protobuf:"varint,1,opt,name=LocalUserExists" json:"LocalUserExists,omitempty"`
	LocalUserEntity *feobjects.CompiledUserEntity `protobuf:"bytes,2,opt,name=LocalUserEntity" json:"LocalUserEntity,omitempty"`
}

func (m *AmbientLocalUserEntityPayload) Reset()                    { *m = AmbientLocalUserEntityPayload{} }
func (m *AmbientLocalUserEntityPayload) String() string            { return proto.CompactTextString(m) }
func (*AmbientLocalUserEntityPayload) ProtoMessage()               {}
func (*AmbientLocalUserEntityPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AmbientLocalUserEntityPayload) GetLocalUserExists() bool {
	if m != nil {
		return m.LocalUserExists
	}
	return false
}

func (m *AmbientLocalUserEntityPayload) GetLocalUserEntity() *feobjects.CompiledUserEntity {
	if m != nil {
		return m.LocalUserEntity
	}
	return nil
}

type AmbientLocalUserEntityResponse struct {
}

func (m *AmbientLocalUserEntityResponse) Reset()                    { *m = AmbientLocalUserEntityResponse{} }
func (m *AmbientLocalUserEntityResponse) String() string            { return proto.CompactTextString(m) }
func (*AmbientLocalUserEntityResponse) ProtoMessage()               {}
func (*AmbientLocalUserEntityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func init() {
	proto.RegisterType((*FEReadyRequest)(nil), "clapi.FEReadyRequest")
	proto.RegisterType((*FEReadyResponse)(nil), "clapi.FEReadyResponse")
	proto.RegisterType((*AmbientsRequest)(nil), "clapi.AmbientsRequest")
	proto.RegisterType((*AmbientsResponse)(nil), "clapi.AmbientsResponse")
	proto.RegisterType((*BackendAmbientStatus)(nil), "clapi.BackendAmbientStatus")
	proto.RegisterType((*FrontendAmbientStatus)(nil), "clapi.FrontendAmbientStatus")
	proto.RegisterType((*InflightStatus)(nil), "clapi.InflightStatus")
	proto.RegisterType((*InflightBoard)(nil), "clapi.InflightBoard")
	proto.RegisterType((*InflightThread)(nil), "clapi.InflightThread")
	proto.RegisterType((*InflightPost)(nil), "clapi.InflightPost")
	proto.RegisterType((*InflightVote)(nil), "clapi.InflightVote")
	proto.RegisterType((*InflightKey)(nil), "clapi.InflightKey")
	proto.RegisterType((*InflightTruststate)(nil), "clapi.InflightTruststate")
	proto.RegisterType((*Inflights)(nil), "clapi.Inflights")
	proto.RegisterType((*AmbientStatusPayload)(nil), "clapi.AmbientStatusPayload")
	proto.RegisterType((*AmbientStatusResponse)(nil), "clapi.AmbientStatusResponse")
	proto.RegisterType((*AmbientLocalUserEntityPayload)(nil), "clapi.AmbientLocalUserEntityPayload")
	proto.RegisterType((*AmbientLocalUserEntityResponse)(nil), "clapi.AmbientLocalUserEntityResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClientAPI service

type ClientAPIClient interface {
	FrontendReady(ctx context.Context, in *FEReadyRequest, opts ...grpc.CallOption) (*FEReadyResponse, error)
	DeliverAmbients(ctx context.Context, in *AmbientsRequest, opts ...grpc.CallOption) (*AmbientsResponse, error)
	SendAmbientStatus(ctx context.Context, in *AmbientStatusPayload, opts ...grpc.CallOption) (*AmbientStatusResponse, error)
	SendAmbientLocalUserEntity(ctx context.Context, in *AmbientLocalUserEntityPayload, opts ...grpc.CallOption) (*AmbientLocalUserEntityResponse, error)
}

type clientAPIClient struct {
	cc *grpc.ClientConn
}

func NewClientAPIClient(cc *grpc.ClientConn) ClientAPIClient {
	return &clientAPIClient{cc}
}

func (c *clientAPIClient) FrontendReady(ctx context.Context, in *FEReadyRequest, opts ...grpc.CallOption) (*FEReadyResponse, error) {
	out := new(FEReadyResponse)
	err := grpc.Invoke(ctx, "/clapi.ClientAPI/FrontendReady", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) DeliverAmbients(ctx context.Context, in *AmbientsRequest, opts ...grpc.CallOption) (*AmbientsResponse, error) {
	out := new(AmbientsResponse)
	err := grpc.Invoke(ctx, "/clapi.ClientAPI/DeliverAmbients", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) SendAmbientStatus(ctx context.Context, in *AmbientStatusPayload, opts ...grpc.CallOption) (*AmbientStatusResponse, error) {
	out := new(AmbientStatusResponse)
	err := grpc.Invoke(ctx, "/clapi.ClientAPI/SendAmbientStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) SendAmbientLocalUserEntity(ctx context.Context, in *AmbientLocalUserEntityPayload, opts ...grpc.CallOption) (*AmbientLocalUserEntityResponse, error) {
	out := new(AmbientLocalUserEntityResponse)
	err := grpc.Invoke(ctx, "/clapi.ClientAPI/SendAmbientLocalUserEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClientAPI service

type ClientAPIServer interface {
	FrontendReady(context.Context, *FEReadyRequest) (*FEReadyResponse, error)
	DeliverAmbients(context.Context, *AmbientsRequest) (*AmbientsResponse, error)
	SendAmbientStatus(context.Context, *AmbientStatusPayload) (*AmbientStatusResponse, error)
	SendAmbientLocalUserEntity(context.Context, *AmbientLocalUserEntityPayload) (*AmbientLocalUserEntityResponse, error)
}

func RegisterClientAPIServer(s *grpc.Server, srv ClientAPIServer) {
	s.RegisterService(&_ClientAPI_serviceDesc, srv)
}

func _ClientAPI_FrontendReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FEReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).FrontendReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clapi.ClientAPI/FrontendReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).FrontendReady(ctx, req.(*FEReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_DeliverAmbients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AmbientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).DeliverAmbients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clapi.ClientAPI/DeliverAmbients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).DeliverAmbients(ctx, req.(*AmbientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_SendAmbientStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AmbientStatusPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).SendAmbientStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clapi.ClientAPI/SendAmbientStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).SendAmbientStatus(ctx, req.(*AmbientStatusPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_SendAmbientLocalUserEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AmbientLocalUserEntityPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).SendAmbientLocalUserEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clapi.ClientAPI/SendAmbientLocalUserEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).SendAmbientLocalUserEntity(ctx, req.(*AmbientLocalUserEntityPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clapi.ClientAPI",
	HandlerType: (*ClientAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FrontendReady",
			Handler:    _ClientAPI_FrontendReady_Handler,
		},
		{
			MethodName: "DeliverAmbients",
			Handler:    _ClientAPI_DeliverAmbients_Handler,
		},
		{
			MethodName: "SendAmbientStatus",
			Handler:    _ClientAPI_SendAmbientStatus_Handler,
		},
		{
			MethodName: "SendAmbientLocalUserEntity",
			Handler:    _ClientAPI_SendAmbientLocalUserEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clapi/clapi.proto",
}

func init() { proto.RegisterFile("clapi/clapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x4e, 0xdb, 0x4a,
	0x14, 0x3d, 0xb9, 0x72, 0xb2, 0x73, 0x20, 0x64, 0x08, 0x60, 0xcc, 0x45, 0x91, 0x75, 0x5a, 0x85,
	0x16, 0x12, 0x94, 0xaa, 0x4f, 0x95, 0xaa, 0x72, 0x6d, 0x11, 0x48, 0x8d, 0x86, 0xb4, 0x0f, 0x7d,
	0x33, 0xf6, 0x00, 0x2e, 0x8e, 0x9d, 0x7a, 0x26, 0x88, 0xfc, 0x46, 0xff, 0xa1, 0x3f, 0xd4, 0x0f,
	0xe8, 0x0f, 0xf4, 0x27, 0x2a, 0x8f, 0x67, 0x7c, 0x99, 0xb8, 0x95, 0x22, 0xf5, 0x05, 0x79, 0x66,
	0xaf, 0xbd, 0xd6, 0xbe, 0xb1, 0x27, 0xd0, 0xb4, 0x5c, 0x73, 0xec, 0xf4, 0xf8, 0xdf, 0xee, 0x38,
	0xf0, 0x99, 0x8f, 0x2a, 0xfc, 0xa0, 0x6f, 0xdc, 0x10, 0xff, 0xfa, 0x33, 0xb1, 0x18, 0xed, 0xc5,
	0x5f, 0x11, 0x42, 0xdf, 0x18, 0x39, 0xa3, 0xd0, 0x8b, 0xb2, 0x60, 0x62, 0x31, 0x7e, 0x27, 0x4c,
	0xc6, 0x6b, 0x58, 0x3a, 0x3b, 0xc5, 0xc4, 0xb4, 0xa7, 0x98, 0x7c, 0x99, 0x10, 0xca, 0x90, 0x06,
	0x0b, 0xa6, 0x6d, 0x07, 0x84, 0x52, 0xad, 0xd0, 0x2e, 0x74, 0x6a, 0x58, 0x1e, 0x11, 0x82, 0xf2,
	0xd8, 0x0f, 0x98, 0x56, 0x6c, 0x17, 0x3a, 0x15, 0xcc, 0xbf, 0x8d, 0x26, 0x34, 0x62, 0x7f, 0x3a,
	0xf6, 0x3d, 0x4a, 0x8c, 0x77, 0xd0, 0x38, 0x1c, 0x5d, 0x3b, 0xc4, 0x63, 0x54, 0x72, 0xbe, 0x84,
	0xea, 0x91, 0x6f, 0x06, 0x76, 0x48, 0x59, 0xea, 0xd4, 0xfb, 0xdb, 0xdd, 0x24, 0x44, 0x81, 0xe5,
	0xf6, 0x53, 0x8f, 0x39, 0x6c, 0x8a, 0x05, 0xd8, 0x40, 0xb0, 0x9c, 0x30, 0x09, 0xf6, 0x35, 0x68,
	0x1d, 0x99, 0xd6, 0x3d, 0xf1, 0x6c, 0x61, 0xba, 0x62, 0x26, 0x9b, 0x50, 0x63, 0x1d, 0x56, 0xcf,
	0x02, 0xdf, 0x63, 0x33, 0x86, 0x1f, 0x05, 0x58, 0x3a, 0xf7, 0x6e, 0x5c, 0xe7, 0xf6, 0x4e, 0x5c,
	0xa1, 0x3d, 0x68, 0x1e, 0xfb, 0xa3, 0xb1, 0x4b, 0x98, 0xe3, 0x7b, 0x03, 0x12, 0x58, 0xc4, 0x63,
	0x3c, 0xd9, 0x0a, 0x9e, 0x35, 0xa0, 0x1d, 0x80, 0xc8, 0x6f, 0x48, 0x1e, 0xa3, 0xe4, 0x6b, 0x38,
	0x75, 0x83, 0xba, 0x80, 0x44, 0x9e, 0xc4, 0x1e, 0x3a, 0x23, 0x42, 0x99, 0x39, 0x1a, 0x6b, 0xe5,
	0x76, 0xa1, 0x53, 0xc2, 0x39, 0x16, 0x74, 0x00, 0x2b, 0x97, 0x26, 0x65, 0x87, 0x56, 0x28, 0x92,
	0x38, 0x54, 0xb8, 0x43, 0x9e, 0x09, 0x6d, 0x41, 0xed, 0xf4, 0x81, 0x78, 0x6c, 0x38, 0x1d, 0x13,
	0xad, 0xca, 0x03, 0x48, 0x2e, 0x8c, 0x7b, 0x58, 0x94, 0xf9, 0xf1, 0xba, 0xa1, 0x7d, 0xa8, 0x46,
	0xe1, 0xf1, 0x9c, 0xea, 0xfd, 0xd5, 0x6e, 0x34, 0x2e, 0xd9, 0x2a, 0x60, 0x01, 0x42, 0xcf, 0xa1,
	0x1a, 0xd5, 0x9d, 0xe7, 0x56, 0xef, 0xaf, 0x74, 0x33, 0x73, 0xc2, 0x39, 0xb1, 0x80, 0x18, 0xa3,
	0xa4, 0x98, 0xc3, 0xbb, 0x80, 0x98, 0x73, 0xab, 0xed, 0x29, 0x6a, 0xad, 0xac, 0x5a, 0x44, 0x1a,
	0xcb, 0x39, 0xf0, 0x9f, 0xe4, 0x19, 0xf8, 0x94, 0xcd, 0x2b, 0xf6, 0x4c, 0x11, 0x43, 0x59, 0xb1,
	0x90, 0x32, 0x4f, 0xea, 0xa3, 0xcf, 0xc8, 0x5f, 0x96, 0x0a, 0x29, 0x63, 0xa9, 0x5b, 0xa8, 0x4b,
	0x96, 0x0b, 0x32, 0x9d, 0x57, 0x69, 0x57, 0x51, 0x6a, 0x66, 0x95, 0x2e, 0xc8, 0x34, 0x16, 0x9a,
	0x00, 0x8a, 0xbb, 0x15, 0x4c, 0x28, 0xa3, 0xcc, 0x9c, 0x3f, 0xb3, 0x03, 0x45, 0x4f, 0x53, 0x3a,
	0x16, 0x13, 0xc7, 0xb2, 0xdf, 0x8a, 0x50, 0x93, 0x64, 0xbc, 0xe3, 0x99, 0x7f, 0xfe, 0x96, 0x22,
	0x27, 0x06, 0x2c, 0xc2, 0xa0, 0x1e, 0x2c, 0x44, 0x33, 0x40, 0xb5, 0x22, 0x87, 0xab, 0xd1, 0x89,
	0x09, 0x91, 0x28, 0xb4, 0x0b, 0x95, 0xb0, 0x8f, 0x54, 0x2b, 0x71, 0xf8, 0x8a, 0x02, 0xe7, 0x3d,
	0x8e, 0x10, 0x21, 0x34, 0xec, 0x03, 0xd5, 0xca, 0xb9, 0x50, 0xde, 0xa3, 0x08, 0x81, 0x9e, 0x42,
	0xf9, 0x82, 0x4c, 0xa9, 0x56, 0xe1, 0x48, 0xa4, 0x20, 0xc3, 0x1a, 0x73, 0x3b, 0x7a, 0x05, 0xf5,
	0xa4, 0x00, 0x54, 0xab, 0x72, 0xf8, 0x86, 0x1a, 0x72, 0x52, 0xa2, 0x34, 0xda, 0xf8, 0x59, 0x80,
	0x56, 0x66, 0x59, 0x0d, 0xcc, 0xa9, 0xeb, 0x9b, 0x36, 0x7a, 0x9f, 0xbf, 0xe4, 0x44, 0xbf, 0x36,
	0x05, 0x7d, 0x1e, 0x04, 0xe7, 0x3a, 0x22, 0xfc, 0x9b, 0xed, 0x28, 0x5a, 0xba, 0x25, 0x18, 0x73,
	0x31, 0x38, 0xdf, 0x15, 0x75, 0x53, 0x4d, 0xd6, 0x4a, 0x9c, 0x67, 0x59, 0x49, 0x9c, 0xe2, 0x04,
	0x12, 0x6e, 0xe8, 0x2c, 0xaf, 0x5c, 0xe9, 0x5f, 0x0b, 0xb0, 0x2d, 0x2c, 0x97, 0xbe, 0x65, 0xba,
	0x1f, 0x28, 0x09, 0xa2, 0x49, 0x92, 0xf5, 0xe8, 0x40, 0x23, 0xb1, 0x3c, 0x3a, 0x61, 0xb7, 0xc3,
	0x52, 0xfc, 0x8b, 0xd5, 0x6b, 0xf4, 0x36, 0x8d, 0x4c, 0x4f, 0x6d, 0xfa, 0xc9, 0x09, 0x77, 0xbc,
	0xe3, 0x12, 0x3b, 0x01, 0x61, 0xd5, 0xcb, 0x68, 0xc3, 0x4e, 0x7e, 0x4c, 0x32, 0xec, 0xfe, 0xf7,
	0x22, 0xd4, 0x8e, 0xdd, 0x10, 0x71, 0x38, 0x38, 0x47, 0x6f, 0x60, 0x51, 0x96, 0x89, 0x3f, 0x87,
	0x48, 0xce, 0x6d, 0xf6, 0x79, 0xd5, 0xd7, 0xd4, 0x6b, 0x51, 0x84, 0x7f, 0xd0, 0x09, 0x34, 0x4e,
	0x88, 0xeb, 0x3c, 0x90, 0x40, 0x3e, 0x7a, 0x48, 0x82, 0x95, 0xf7, 0x54, 0x5f, 0x9f, 0xb9, 0x8f,
	0x59, 0x06, 0xd0, 0xbc, 0x9a, 0x69, 0xd5, 0x66, 0x16, 0x9f, 0x19, 0x36, 0x7d, 0x2b, 0xcf, 0x98,
	0x62, 0xbc, 0x07, 0x3d, 0xc5, 0xa8, 0x54, 0x03, 0xfd, 0x9f, 0xf5, 0xce, 0x6f, 0xa0, 0xfe, 0xe4,
	0x8f, 0xa8, 0x44, 0xec, 0x48, 0xff, 0xa4, 0x99, 0x84, 0xdd, 0x91, 0x60, 0xdf, 0xf2, 0x03, 0xd2,
	0x8b, 0x76, 0x4c, 0xf4, 0x73, 0xe7, 0xba, 0xca, 0x4f, 0x2f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xb6, 0xd6, 0x69, 0x8f, 0x04, 0x09, 0x00, 0x00,
}
