// export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
// export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const BROWSER_BACK = 'BROWSER_BACK'
export const BROWSER_FORWARD = 'BROWSER_FORWARD'
